---
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Album"
          AttributeType: "S"
        -
          AttributeName: "Artist"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Album"
          KeyType: "HASH"
        -
          AttributeName: "Artist"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      #TableName: "myTableName"
      TimeToLiveSpecification:
          AttributeName: "TTL"
          Enabled: True
      Tags:
        -
          Key: usecase
          Value: test
        -
          #
          # Change this to any value after restore to let CF sync the missing
          # attributes from the template
          #
          Key: restored
          Value: "Wed Oct 10 09:41:17 CEST 2018"
Outputs:
  TableName:
    Description: Name of Table
    Value: !Ref DynamoDBTable
