---
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  # VPC:
  #    Type: AWS::EC2::VPC::Id
  #    Description: VPC to launch the instance into.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet to launch the instance into.
  SshKeyName:
    Type: String
    Default: ''

Conditions:
  HasSshKey: !Not [!Equals [!Ref SshKeyName, ""]]

Mappings:
  # you can choose from: https://aws.amazon.com/de/amazon-linux-ami/ too
  # This is for static mapping of AMI Ids
  AWSRegion2AMI:
    us-east-1:
      AmazonLinux2: ami-0e6d2e8684d4ccb3e
    eu-west-1:
      AmazonLinux2: ami-0eafb5ee12a2cbffc

Resources:

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [AWSRegion2AMI, !Ref 'AWS::Region', 'AmazonLinux2']
      InstanceType: t2.micro
      # SecurityGroupIds:
      #   - !GetAtt InstanceSecurityGroup.GroupId
      SubnetId:
        Ref: SubnetId
      KeyName: !If [ HasSshKey, !Ref SshKeyName, !Ref 'AWS::NoValue' ]
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install ec2-net-utils -y
          ec2ifup eth1
          service httpd start

  # InstanceSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupDescription: Enable access to 8080 from everywhere
  #     SecurityGroupIngress:
  #     - IpProtocol: tcp
  #       FromPort: 8080
  #       ToPort: 8080
  #       CidrIp: 0.0.0.0/0
